### ISSUE TITLE
Breadcrumbs for cloned notes

### ISSUE THREAD

**Issue by Nriver** [rauenzi/Trilium-Breadcrumbs#1]
As mentioned here. https://github.com/zadam/trilium/issues/3754#issuecomment-1683240849

> The navigation seems only get the first path of multiple note paths even if I'm on the second or the third path.

**Comment by zerebos** [comment]
Thanks for reporting! I think I just forgot to await the note complement. Can you try changing
```js
async refreshWithNote(note) {
    await this.makeBreadcrumb(note);
}
```

to

```js
async refreshWithNote(note) {
    await note.getNoteComplement();
    await this.makeBreadcrumb(note);
}
```

and see if that fixes it for you? It seems to on my end.

**Comment by Nriver** [comment]
The path is changing now. But I there path is not right all the time. I tested with a brand new database on 0.60.4.

The initial state could be wrong. As `me` is under `dad`.

![1](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/6752679/0f60f311-8bfd-464a-a255-e2bac9bcdcfb)

Switch between `me` and `mom`, the path changes all the time.

![2](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/6752679/25645c73-78c4-442d-8581-4e22671876e3)

[play.zip](https://github.com/rauenzi/Trilium-Breadcrumbs/files/12376015/play.zip)

**Comment by zerebos** [comment]
Alright one more thing to try....

Change
```js
        const notePath = note.getBestNotePath();
```

to

```js
        const notePath = api.getActiveContextNotePath().split("/");
```

inside `makeBreadcrumb()`

**Comment by Nriver** [comment]
It's working correctly now, thank you!
