### ISSUE TITLE
The keyword "const" is reserved

### ISSUE THREAD

**Issue by Vvoronwe** [rauenzi/Trilium-Breadcrumbs#10]
Hello there!

I followed the install instructions, created a new note, copied the info from the widget and changed the attributes to JS Frontend and #widget, but am getting an error when I try to run it. 

At the first line of "const TPL = `<div id="breadcrumbs-bar"

, a red x appears stating "parsing error: the keyword 'const' is reserved'. This is the only widget I will have installed outside of default Trilium, and I am not experienced with coding. 

Is there a particular step I am missing? 

Thanks for your time

**Comment by zerebos** [comment]
Can you provide a screenshot? Also what version of Trilium is this?

Also by run do you mean clicking the run button? You should not do that, just add the `#widget` attribute and reload Trilium with ctrl+r

**Comment by Vvoronwe** [comment]
Yeah! In the screenshot its showing the root/trilium demo/tech/breadcrumbs but it shows that for -all- notes. 

![image](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/157245310/68fea1b4-de64-49d8-bc0b-1f6569fd257c)


Ah okay, I didn't know that I needed to use ctrl+r, thank you for that! 

For the version, it's the latest version 0.62.5

**Comment by zerebos** [comment]
Do you mean it shows specifically ` root/trilium demo/tech/breadcrumbs` for all notes? or breadcrumbs in general?

**Comment by Vvoronwe** [comment]
It was showing that for all notes, but I was able to fix it by doing a fresh install. Not sure why that worked, but it did!
