### ISSUE TITLE
Breadcrumbs not updating?

### ISSUE THREAD

**Issue by nema69** [rauenzi/Trilium-Breadcrumbs#11]
Hi, 
I was successfully able to install this widget and the breadcrumbs do show up, but they only change to the current path when I refresh the gui with ctrl+r. Im on Version 0.62.4. Am I missing something? I set the note type to JS frontend and added the #widget attribute. 
I appreciate your help :)

**Comment by zerebos** [comment]
Hi I am away from home and currently unable to look into this. This should be working on 0.62.4

**Comment by nema69** [comment]
Issue fixed itself. Feel free to delete this thread. Widget is awesome by the way, should definitely be part of the base application :)
