### ISSUE TITLE
The forward and backward icons are missing

### ISSUE THREAD

**Issue by Joackk** [rauenzi/Trilium-Breadcrumbs#12]
I can't get my forward and backward icons to be seen, I'm not sure if it's a new version of trilium that's causing this
But they just can't be seen, the functionality is still there and they still show the name when I mouse over it
![image](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/45162558/9d9acf46-ae8f-4642-bca5-42634607bda1)

**Comment by zerebos** [comment]
What theme are you using?

**Comment by Joackk** [comment]
> What theme are you using?

blue，他在新版本中已经正常了
