### ISSUE TITLE
Works great, exactly what I was looking for. It will be more convenient if you can add a forward and backward button in the front

### ISSUE THREAD

**Issue by SiriusXT** [rauenzi/Trilium-Breadcrumbs#3]
Works great, exactly what I was looking for. It will be more convenient if you can add a forward and backward button in the front

**Comment by Nriver** [comment]
Nice idea.

**Comment by zerebos** [comment]
Can you test this version and see if it works as you expect? I wasn't sure if you meant it to navigate the tree or to act as forward/backward history but I went with history.

The buttons should be hidden by default, just add the `#history` label to the widget to enable them.

```js
/**
 * A widget to show note breadcrumbs at the bottom of the page.
 */
const TPL = `<div style="display: flex;align-items:center;gap:10px;padding: 10px; border-top: 1px solid var(--main-border-color); contain: none;">
<div id="history-buttons">
<button onclick="window.history.back()" class="tree-floating-button bx bx-left-arrow-circle tree-settings-button" title="Go Back"></button>
<button onclick="window.history.forward()" class="tree-floating-button bx bx-right-arrow-circle tree-settings-button" title="Go Back"></button>
</div>
<div id="breadcrumbs"></div>
</div>`;

const styles = `
/* Place your CSS below this */



/* Place your CSS above this */`;


class BreadcrumbWidget extends api.NoteContextAwareWidget {
    get position() {return 100;}
    get parentWidget() {return "center-pane";}

    constructor() {
        super();
        this.title = "";
    }

    isEnabled() {
        if (!super.isEnabled()) return false;
        const widgetDisable = api.startNote.hasLabel("disable");
        const noteDisable = this.note.hasLabel("breadcrumbsDisable");
        return !widgetDisable && !noteDisable;
    }

    doRender() {
        this.$widget = $(TPL);
        this.$breadcrumbs = this.$widget.find("#breadcrumbs");
        this.updateStyles();
        this.cssBlock(styles);
        return this.$widget;
    }

    async refreshWithNote() {
        await this.makeBreadcrumb();
    }

    async entitiesReloadedEvent({loadResults}) {
        if (loadResults.attributes.length) this.updateStyles();
        if (!this.note) return this.title = "";
        if (!this.title) this.title = this.note.title;
        if (this.note.title != this.title) {
            this.title = this.note.title;
            this.refresh();
        }
    }

    async makeBreadcrumb() {
        this.$breadcrumbs.empty();
        const notePath = api.getActiveContextNotePath().split("/");
        for (let n = 0; n < notePath.length; n++) {
            const path = notePath.slice(0, n + 1);
            const link = await api.createNoteLink(path.join("/"));
            this.$breadcrumbs.append(link);
            if (n < (notePath.length - 1)) this.$breadcrumbs.append(" / ");
        }
    }

    updateStyles() {
        const buttonWrapper = this.$widget.find("#history-buttons");
        if (!buttonWrapper) return; // This should never happen but... just in case
        const isVisible = buttonWrapper.css("display") !== "none";
        const shouldHide = !api.startNote.hasLabel("history");
        if (isVisible && shouldHide) buttonWrapper.hide();
        if (!isVisible && !shouldHide) buttonWrapper.show();
    }
}

module.exports = new BreadcrumbWidget();
```

**Comment by SiriusXT** [comment]
![图片](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/37627919/c419c288-63b6-4d65-ad06-366063c14bad)
What I think is something like this, there are two buttons in front of the root, which means forward and backward, similar to a browser

**Comment by zerebos** [comment]
![image](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/6865942/e9a8ce44-4fb9-4904-8db1-291a26649fed)

Yes that's what this does exactly!

**Comment by Nriver** [comment]
Looks nice. 
I tweaked it a little bit.

![ksnip_20230818-175400](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/6752679/98077d7f-af0c-4327-8bef-8a381d98698d)

**Comment by SiriusXT** [comment]
Just now I added the wrong tag, now it works, great

**Comment by SiriusXT** [comment]
> 看起来不错。 我稍微调整了一下。
> 
> ![ksnip_20230818-175400](https://user-images.githubusercontent.com/6752679/261572023-98077d7f-af0c-4327-8bef-8a381d98698d.png)

how to make it show above

**Comment by Nriver** [comment]
I just pushed my mods here https://github.com/Nriver/Trilium-Breadcrumbs/blob/main/src/widget.js

You can add a `#top` label to move it to the top.

**Comment by zerebos** [comment]
I liked the idea of moving it to the top a lot, feels like a much better fit for it! I think I'll make that the default. And I liked the tag-style links you did there, Nriver, and took inspiration for my own iteration.

https://github.com/rauenzi/Trilium-Breadcrumbs/assets/6865942/4fe328f6-9a74-4c4d-9c4d-e76524ccbdfb


https://github.com/rauenzi/Trilium-Breadcrumbs/assets/6865942/e3578d3d-78d9-4c32-84d6-063023a02f5f

**Comment by Nriver** [comment]
Wow, you made the buttons look better.  The animation looks nice.

**Comment by zerebos** [comment]
Thanks, I wanted to be fancy 😄
