### ISSUE TITLE
Yeat another awesome widget! One issue

### ISSUE THREAD

**Issue by sottey** [rauenzi/Trilium-Breadcrumbs#4]
Love the markdown viewer and I am now loving the Breadcrumbs!

I just wanted to mention one issue which is that the "#top|#bottom" usage is overloading the Sorted functionality. If you have a node sorted, you can specify "#top" on a child note to force it to the top, regardless of sort.

I would propose changing it to something like "#breadcrumbOrder=top" or something like that. Of course, I also think that the sorted #top attribute could be changed to something less generic, but that would be a Trilium change.

For now, I just changed line 65 of the widget code so that the default (if no attribute is present) to 100 instead of 50 to force everything to the bottom.

Thanks again for the amazing tools!
Sean

**Comment by zerebos** [comment]
Thanks for catching this! I don't using the sorting often.
