### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by SiriusXT** [rauenzi/Trilium-Breadcrumbs#5]
There is a bug in the 61.5-beta version, which causes the software to restart automatically after 30 seconds after each note change
![图片](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/37627919/7c008fea-3171-48e2-a428-4edb1cc71171)
![图片](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/37627919/bb9a9642-af10-4e13-8f5a-331980083577)

**Comment by zerebos** [comment]
Yes this is a change in the beta for the load results object, I guess I can technically support both versions

**Comment by SiriusXT** [comment]
After the update, it seems that sometimes it will not be displayed, such as opening two notes at the same time, and then pressing F5 to restart, the first note will be displayed, and it will not be displayed when switching to another tab

**Comment by zerebos** [comment]
Maybe this is a further issue with the beta? or an issue with reloading? May require some additional testing but that doesn't sound like something introduced by this one line change
