### ISSUE TITLE
Breadcrumbs repeat (randomly)

### ISSUE THREAD

**Issue by deajan** [rauenzi/Trilium-Breadcrumbs#7]
Upgraded to Trilium 0.61.7-beta this morning in hope to get rid of some nasty canvas bugs...

I noticed that "sometimes", I get the breadcrumbs like 3 times in a row, eg:

![image](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/4681318/507b2a09-937e-466a-959b-1387e036d9f7)
I left the folder hierarchy visible in the screenshot so you can see that of course I'm not repeating 3 times every folder name ;)

Of course I am myself not able to reproduce this properly, a trilium reboot later it worked okay... Just asking if you might have an idea what might be the culprit ?

**Comment by zerebos** [comment]
Yeah this seems to happen sometimes when the note has a refresh event, I'm still tracking down the exact issue and how to fix it!

**Comment by zerebos** [comment]
Let me know if this still happens with 0.62.X @deajan, how widgets are handled was changed so it should be a bit more stable.

**Comment by deajan** [comment]
Currently running 0.6.2, will let you know if there are behavior changes. Thx

**Comment by banjuer** [comment]
still happens with 0.63.5, when changing note's type it will happen

**Comment by deajan** [comment]
This particular problem didn't happen to me in a while.
But I do have random disappearing breadcrumbs that usually a F5 refresh fixes. By random I mean that I really cannot find any pattern behind this.

**Comment by zerebos** [comment]
Please try the latest version, it should fix all the issues mentioned here. It's a small change but a necessary one. Apparently while I made sure the changes to Trilium got in that I mentioned in https://github.com/rauenzi/Trilium-Breadcrumbs/issues/7#issuecomment-1815752316 I forgot to update this widget to actually take advantage of that change.
