### ISSUE TITLE
Breadcrumbs not always rendered

### ISSUE THREAD

**Issue by jwhonce** [rauenzi/Trilium-Breadcrumbs#8]
These all happen with multiple tabs opened, and I am navigating from tab to tab. Reloading the frontend always renders the expected breadcrumbs.

* Journal Day notes have no arrow buttons or crumbs. 
* Notes in the Inbox show just the arrow buttons, no crumbs. 
* Rendered Notes show the arrow buttons, no crumbs.
* Text Notes show the arrow buttons, no crumbs. Once reloaded, the breadcrumbs remain until the other notes where they only appear on reloads.

Trilium 0.60.4 running client from flatpak on Fedora 38. Sync'ing against a Fedora 38 server running 0.60.4 from a container.

**Comment by zerebos** [comment]
Having multiple tabs or split panes or windows open can and will definitely cause this. See https://github.com/zadam/trilium/issues/4274 I would imagine that change will be in 0.62

**Comment by jwhonce** [comment]
Will reopen if needed when tested against 0.62.

**Comment by zerebos** [comment]
Sounds good! I know I tested it myself locally and it fixes these types of issues.
