### ISSUE TITLE
How do I set up the menu to automatically hide after clicking on the dropdown menu item?

### ISSUE THREAD

**Issue by tiger7651** [rauenzi/Trilium-Breadcrumbs#9]
How do I set up the menu to automatically hide after clicking on the dropdown menu item?
![image](https://github.com/rauenzi/Trilium-Breadcrumbs/assets/150779117/1bb33145-3864-48d0-a4d9-7b6847028bc7)

**Comment by zerebos** [comment]
Unfortunately, that menu is made by Trilium itself since the link is generated using their API. I would suggest you make a request there first. If it's not accepted then maybe I'll do a hacky workaround.
